# This file must be sourced, not executed, so these variables will be
# available to the calling script

export WORKDIR="/home/user/Data/workdir"
export LOGDIR=$WORKDIR"/logdir"

## Input products/listfiles

export DATA_IM_LF="CalibratedFrames.json"
export DATA_STACK_PROD="DpdVisStackedFrame.xml"
export DTC_LF="DetectionsCatalogs.json"

## Intermediate files/listfiles

# Generated by SHE_MER
export SEG_LF="MosaicFrames.json"
export SEG_STACK_F="EUC_SHE_SHE_Mosaic_Stack_2018315T15328.0Z_00.00.fits"

# Generated by SHE_PSM
export PSF_LF="EUC_SHE_PSF_IMTAB.json"

# Generated by SHE_EstimateShears
export SE_PROD="EUC_SHE_SHEAR_ESTIMATES.xml"

# Generated by SHE_ValidateShears
export CVSE_PROD="EUC_SHE_VAL_SHEAR_ESTIMATES.xml"