#/bin/bash

E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp0Sp0Template.conf --workdir /home/user/Work/workspace_Ep0Pp0Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp1Pp0Sp0Template.conf --workdir /home/user/Work/workspace_Ep1Pp0Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp2Pp0Sp0Template.conf --workdir /home/user/Work/workspace_Ep2Pp0Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEm1Pp0Sp0Template.conf --workdir /home/user/Work/workspace_Em1Pp0Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEm2Pp0Sp0Template.conf --workdir /home/user/Work/workspace_Em2Pp0Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp1Sp0Template.conf --workdir /home/user/Work/workspace_Ep0Pp1Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp2Sp0Template.conf --workdir /home/user/Work/workspace_Ep0Pp2Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pm1Sp0Template.conf --workdir /home/user/Work/workspace_Ep0Pm1Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pm2Sp0Template.conf --workdir /home/user/Work/workspace_Ep0Pm2Sp0
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp0Sp1Template.conf --workdir /home/user/Work/workspace_Ep0Pp0Sp1
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp0Sp2Template.conf --workdir /home/user/Work/workspace_Ep0Pp0Sp2
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp0Sm1Template.conf --workdir /home/user/Work/workspace_Ep0Pp0Sm1
E-Run SHE_Pipeline 0.3 SHE_Pipeline_Run --pipeline bias_measurement --isf AUX/SHE_Pipeline/bias_measurement_isf.txt --args config_template AUX/SHE_GST_PrepareConfigs/SensitivityEp0Pp0Sm2Template.conf --workdir /home/user/Work/workspace_Ep0Pp0Sm2
